default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: practplan_development

test:
  <<: *default
  database: practplan_test

production:
  <<: *default
  database: practplan_production
  username: practplan
  password: <%= ENV['PRACTPLAN_DATABASE_PASSWORD'] %>
